<?php

namespace GP247\Front\Admin\Livewire;

use GP247\Core\AdminShell\Infrastructure\FormComponent;
use GP247\Front\Models\FrontLayoutBlock;
use GP247\Front\Models\FrontPage;
use Illuminate\Contracts\View\View;

/**
 * Layout block create/edit form (front-admin Unit) — modern port of the legacy
 * AdminLayoutBlockController create/edit: name, position, page (comma-separated
 * page aliases or '*'), text (HTML/view name), type (html|view|page), sort and
 * status. Domain unchanged (FrontLayoutBlock). Gated by `admin_layout_block`.
 *
 * The "text" content field switches per type on Livewire re-render:
 *   html  → TinyMCE rich editor
 *   view  → select of template block view files (blocks/*.blade.php)
 *   page  → select of store page aliases
 * No jQuery, no AJAX — lists are resolved server-side in render().
 *
 * @aidlc-unit front-admin
 * @aidlc-story US-FADM-004
 * @aidlc-adr ADR-006, ADR-007
 */
class LayoutBlockForm extends FormComponent
{
    protected ?string $permission = 'admin_layout_block';

    /**
     * @var array<int, string> `text` holds admin-authored HTML markup when
     * type=html (rendered raw on the storefront); it must not be
     * htmlspecialchars-escaped by the shared save() boundary sanitization.
     */
    protected array $richFields = ['text'];

    /** @var array<string, mixed> */
    public array $form = [
        'name' => '',
        'position' => '',
        'page' => [],
        'text' => '',
        'type' => 'html',
        'sort' => 0,
        'status' => 1,
    ];

    /**
     * @param string|null $id Layout block id to edit; null to create.
     * @return void
     */
    public function mount(?string $id = null): void
    {
        parent::mount();

        if ($id !== null) {
            $block = FrontLayoutBlock::findOrFail($id);
            $this->editingId = (string) $block->id;
            $this->form = [
                'name' => (string) $block->name,
                'position' => (string) $block->position,
                'page' => $block->page === '*' ? ['*'] : array_values(array_filter(explode(',', (string) $block->page))),
                'text' => (string) $block->text,
                'type' => $block->type ?: 'html',
                'sort' => (int) $block->sort,
                'status' => (int) $block->status,
            ];
        }
    }

    /**
     * @return array<string, mixed>
     */
    protected function rules(): array
    {
        return [
            'form.name' => ['required', 'string', 'max:255'],
            'form.position' => ['required', 'string', 'max:255'],
            'form.page' => ['required', 'array', 'min:1'],
            'form.text' => ['required', 'string'],
            'form.type' => ['required', 'in:html,view,page'],
            'form.sort' => ['required', 'numeric', 'min:0'],
        ];
    }

    /**
     * @param array<string, mixed> $data Sanitised form values.
     * @return void
     */
    protected function persist(array $data): void
    {
        $attributes = [
            'name' => $data['name'],
            'position' => $data['position'],
            'page' => in_array('*', (array) ($data['page'] ?? [])) ? '*' : implode(',', (array) ($data['page'] ?? [])),
            'text' => $data['text'],
            'type' => $data['type'],
            'sort' => (int) ($data['sort'] ?? 0),
            'status' => empty($data['status']) ? 0 : 1,
            // WHY: mirror the legacy store binding — scope to the current admin
            // store when present, else fall back to root store id (0) so a
            // single-store install behaves like the brownfield screen.
            'store_id' => session('adminStoreId') ?? 0,
            // WHY: the column is NOT NULL with no default; bind the active store's
            // template (legacy derives the block's template from the store).
            'template' => function_exists('gp247_store_info') ? (string) gp247_store_info('template') : '',
        ];

        // WHY: id is auto-generated by the model's creating() hook (UuidTrait),
        // so it is never set here.
        if ($this->editingId !== null) {
            $block = FrontLayoutBlock::findOrFail($this->editingId);
            $block->update($attributes);
        } else {
            FrontLayoutBlock::create($attributes);
        }
    }

    /**
     * Save, then return to the list with a flash.
     *
     * @return void
     */
    public function save(): void
    {
        parent::save();

        session()->flash('gp247_admin_success', gp247_language_render('admin.core.save_success'));
        $this->redirectRoute('admin_layout_block.index', navigate: true);
    }

    /**
     * Set the block type and reset the text field so stale content
     * (e.g. HTML markup) does not carry over into a view-name picker.
     *
     * @param string $type One of html|view|page.
     * @return void
     *
     * @aidlc-unit front-admin
     * @aidlc-story US-FADM-004
     */
    public function selectType(string $type): void
    {
        $this->form['type'] = in_array($type, ['html', 'view', 'page'], true) ? $type : 'html';
        $this->form['text'] = '';
    }

    /**
     * Return available block view files from the active store's template
     * (mirrors AdminLayoutBlockController::getListViewBlock).
     *
     * @return array<string, string>
     *
     * @aidlc-unit front-admin
     * @aidlc-story US-FADM-004
     */
    protected function getListViewBlock(): array
    {
        $storeId = session('adminStoreId');
        $template = function_exists('gp247_store_info')
            ? (string) gp247_store_info(key: 'template', storeId: $storeId)
            : '';
        $arrView = [];
        foreach (glob(app_path() . '/GP247/Templates/' . $template . '/blocks/*.blade.php') ?: [] as $file) {
            $name = substr(basename($file), 0, -10);
            $arrView[$name] = $name;
        }
        return $arrView;
    }

    /**
     * Return page alias list for the active store
     * (mirrors AdminLayoutBlockController::getListPageBlock).
     *
     * @return array<int, string>
     *
     * @aidlc-unit front-admin
     * @aidlc-story US-FADM-004
     */
    protected function getListPageBlock(): array
    {
        return (new FrontPage)->getListPageAlias(session('adminStoreId'));
    }

    /**
     * Build options array for the position single-select from config.
     *
     * @return array<int, array{id: string, label: string}>
     *
     * @aidlc-unit front-admin
     * @aidlc-story US-FADM-004
     */
    protected function positionOptions(): array
    {
        $opts = [];
        foreach (config('gp247-config.front.layout_position', []) as $code => $langKey) {
            $opts[] = ['id' => (string) $code, 'label' => gp247_language_render($langKey)];
        }
        return $opts;
    }

    /**
     * Build options array for the page-scope multi-select: '*' (all) first,
     * then each store page alias, formatted for <x-gp247::searchable-select>.
     *
     * @return array<int, array{id: string, label: string}>
     *
     * @aidlc-unit front-admin
     * @aidlc-story US-FADM-004
     */
    protected function pageOptions(): array
    {
        $opts = [['id' => '*', 'label' => gp247_language_render('admin.layout_block_page.all')]];
        foreach ($this->getListPageBlock() as $alias) {
            $opts[] = ['id' => $alias, 'label' => $alias];
        }
        return $opts;
    }

    /**
     * Build options array for the type=page content single-select (no wildcard).
     *
     * @return array<int, array{id: string, label: string}>
     *
     * @aidlc-unit front-admin
     * @aidlc-story US-FADM-004
     */
    protected function pageViewOptions(): array
    {
        return array_map(
            fn($alias) => ['id' => $alias, 'label' => $alias],
            $this->getListPageBlock()
        );
    }

    /**
     * @return array{name: string, url: string}
     */
    protected function listCrumb(): array
    {
        return ['name' => gp247_language_render('admin.layout_block.title'), 'url' => route('admin_layout_block.index')];
    }

    /**
     * @return View
     */
    public function render(): View
    {
        return view('gp247-front-admin::layout-block-form', [
            'types' => ['html' => 'Html', 'view' => 'View', 'page' => 'Page'],
            'positionOptions' => $this->positionOptions(),
            'viewBlocks' => $this->getListViewBlock(),
            'pageOptions' => $this->pageOptions(),
            'pageViewOptions' => $this->pageViewOptions(),
        ])->layout('gp247-admin::layouts.admin', [
            'title' => gp247_language_render($this->editingId !== null ? 'action.edit' : 'admin.layout_block.add_new'),
            'breadcrumb' => $this->listCrumb(),
        ]);
    }
}
